version: '3'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - redis
    network_mode: host
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    network_mode: host
